[package]
name = "portal-gateway"
version = "0.1.0"
authors = ["idealwebsolutions <alex@idealwebsolutions.co>"]

[dependencies]
nanomsg = "0.6"
rust-crypto = "0.2"
futures = "0.1"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
time = "0.1"
crossbeam = "0.2"
log = "0.3.6"
